/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import modelo.Tablachida;
import modelo.reloj;
import java.awt.Color;
import java.awt.Font;
import java.text.DateFormat;
import java.util.Date;
import java.util.Stack;
import javax.swing.UIManager;

import javax.swing.table.TableColumnModel;
import modelo.Producto;
import modelo.Ticket;

/**
 *
 * @author Axel Reyez
 */
public class Ventana extends javax.swing.JPanel {

   public Tablachida modelo;
       public Stack<Producto> pila ;
    public Stack<Producto> pila1 ;
    
             
    
    public Ventana()  {
      
             
  Font font = new Font(Font.SANS_SERIF, Font.PLAIN, 25);
UIManager.put("OptionPane.messageFont", font);
UIManager.put("OptionPane.buttonFont", font);

        initComponents();
        ComandaT.setAlignmentY(2);
        
        String cabecera []={"Producto","Precio"};
        reloj hilo=new reloj(dia);
        hilo.start();
String datos[][]={};

boolean t=true;
boolean f=false;

modelo = new Tablachida(datos,cabecera);
tabla.setModel(modelo);
TableColumnModel columnModel = tabla.getColumnModel();
columnModel.getColumn(0).setPreferredWidth(480);
DateFormat df= DateFormat.getDateInstance();
Date Fecha = new Date();
tabla.setRowHeight(25);
 this.Ccorral.setVisible(f);
 this.Cfierro.setVisible(f);
 this.cEspecial.setVisible(f);
 this.Extras.setVisible(f);
 this.Sabor.setVisible(f);
 this.Pan.setVisible(f);
 this.Tamaño.setVisible(f);
 this.guarnicion.setVisible(f);
 this.Termino.setVisible(f);
 this.Agregar.setEnabled(f);
 this.Actualizar.setVisible(f);


   
DateFormat df2 = DateFormat.getDateInstance(DateFormat.LONG);
this.Fecha.setText(df2.format(Fecha));
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        Eliminar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Duplicar = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mover = new javax.swing.JMenu();
        MoverA1 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        MoverA2 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        MoverA3 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        MoverA4 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        MoverA5 = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        MoverA6 = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        MoverA7 = new javax.swing.JMenuItem();
        ClienteT = new javax.swing.JTextField();
        CancelarO = new javax.swing.JButton();
        dia = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        FinalizarO = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Fecha = new javax.swing.JLabel();
        ComandaT = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        Corral = new javax.swing.JRadioButton();
        Fierro = new javax.swing.JRadioButton();
        Bebida = new javax.swing.JRadioButton();
        Especial = new javax.swing.JRadioButton();
        Extra = new javax.swing.JRadioButton();
        Ccorral = new javax.swing.JComboBox();
        guarnicion = new javax.swing.JComboBox();
        Termino = new javax.swing.JComboBox();
        Pan = new javax.swing.JComboBox();
        Cfierro = new javax.swing.JComboBox();
        Sabor = new javax.swing.JComboBox();
        Tamaño = new javax.swing.JComboBox();
        Extras = new javax.swing.JComboBox();
        Agregar = new javax.swing.JButton();
        cEspecial = new javax.swing.JComboBox();
        Cliente = new javax.swing.JLabel();
        Actualizar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CambioT = new javax.swing.JFormattedTextField();
        RecibidoT = new javax.swing.JFormattedTextField();
        TotalT = new javax.swing.JFormattedTextField();

        Eliminar.setText("Eliminar");
        jPopupMenu1.add(Eliminar);
        jPopupMenu1.add(jSeparator1);

        Duplicar.setText("Duplicar");
        jPopupMenu1.add(Duplicar);
        jPopupMenu1.add(jSeparator2);

        mover.setText("Mover");

        MoverA1.setText("Mesa 1");
        mover.add(MoverA1);
        mover.add(jSeparator3);

        MoverA2.setText("Mesa 2");
        mover.add(MoverA2);
        mover.add(jSeparator4);

        MoverA3.setText("Mesa 3");
        mover.add(MoverA3);
        mover.add(jSeparator5);

        MoverA4.setText("Mesa 4");
        mover.add(MoverA4);
        mover.add(jSeparator6);

        MoverA5.setText("Mesa 5");
        mover.add(MoverA5);
        mover.add(jSeparator7);

        MoverA6.setText("Out 1");
        mover.add(MoverA6);
        mover.add(jSeparator8);

        MoverA7.setText("Out 2");
        mover.add(MoverA7);

        jPopupMenu1.add(mover);

        ClienteT.setBackground(new java.awt.Color(51, 51, 55));
        ClienteT.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        ClienteT.setForeground(new java.awt.Color(0, 0, 0));
        ClienteT.setText("-");

        CancelarO.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        CancelarO.setForeground(new java.awt.Color(0, 0, 0));
        CancelarO.setText("Cancelar orden");
        CancelarO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarOActionPerformed(evt);
            }
        });

        dia.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        dia.setForeground(new java.awt.Color(255, 255, 255));
        dia.setText("jLabel4");

        tabla.setBackground(new java.awt.Color(255, 255, 255));
        tabla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tabla.setFont(new java.awt.Font("David", 0, 14)); // NOI18N
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Producto                                 ", "Cantidad", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        tabla.setComponentPopupMenu(jPopupMenu1);
        tabla.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(tabla);

        FinalizarO.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        FinalizarO.setForeground(new java.awt.Color(0, 0, 0));
        FinalizarO.setText("Finalizar orden");
        FinalizarO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizarOActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("#Comanda");

        Fecha.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        Fecha.setForeground(new java.awt.Color(255, 255, 255));
        Fecha.setText("jLabel3");

        ComandaT.setEditable(false);
        ComandaT.setFont(new java.awt.Font("Thonburi", 1, 18)); // NOI18N
        ComandaT.setForeground(new java.awt.Color(0, 0, 0));
        ComandaT.setText("1");
        ComandaT.setDragEnabled(true);
        ComandaT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComandaTActionPerformed(evt);
            }
        });

        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });

        buttonGroup1.add(Corral);
        Corral.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        Corral.setText("Corral");
        Corral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorralActionPerformed(evt);
            }
        });

        buttonGroup1.add(Fierro);
        Fierro.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        Fierro.setText("Fierro");

        buttonGroup1.add(Bebida);
        Bebida.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        Bebida.setText("Bebidas");

        buttonGroup1.add(Especial);
        Especial.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        Especial.setText("Especial");
        Especial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspecialActionPerformed(evt);
            }
        });

        buttonGroup1.add(Extra);
        Extra.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        Extra.setText("Extra");

        Ccorral.setFont(new java.awt.Font("Rockwell", 0, 13)); // NOI18N
        Ccorral.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Corral" }));
        Ccorral.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CcorralItemStateChanged(evt);
            }
        });

        guarnicion.setFont(new java.awt.Font("Rockwell", 0, 13)); // NOI18N
        guarnicion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Guarnicion" }));

        Termino.setFont(new java.awt.Font("Rockwell", 0, 13)); // NOI18N
        Termino.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Termino" }));

        Pan.setFont(new java.awt.Font("Rockwell", 0, 13)); // NOI18N
        Pan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pan/Tortilla" }));

        Cfierro.setFont(new java.awt.Font("Rockwell", 0, 13)); // NOI18N
        Cfierro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fierro" }));

        Sabor.setFont(new java.awt.Font("Rockwell", 0, 13)); // NOI18N
        Sabor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sabor" }));

        Tamaño.setFont(new java.awt.Font("Rockwell", 0, 13)); // NOI18N
        Tamaño.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tamaño" }));

        Extras.setFont(new java.awt.Font("Rockwell", 0, 13)); // NOI18N
        Extras.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Extras" }));

        Agregar.setFont(new java.awt.Font("Rockwell", 0, 17)); // NOI18N
        Agregar.setText("Agregar");
        Agregar.setToolTipText("");

        cEspecial.setFont(new java.awt.Font("Rockwell", 0, 13)); // NOI18N
        cEspecial.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Especial", " " }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(Ccorral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cfierro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guarnicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(Pan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(Termino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(Sabor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Tamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Extras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Bebida)
                            .addComponent(Extra)
                            .addComponent(Corral)
                            .addComponent(Fierro)
                            .addComponent(Especial))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ccorral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guarnicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Termino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cfierro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sabor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Extras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(Corral)
                .addGap(18, 18, 18)
                .addComponent(Fierro)
                .addGap(18, 18, 18)
                .addComponent(Especial)
                .addGap(18, 18, 18)
                .addComponent(Bebida)
                .addGap(18, 18, 18)
                .addComponent(Extra, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Cliente.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        Cliente.setForeground(new java.awt.Color(255, 255, 255));
        Cliente.setText("Cliente");

        Actualizar.setText("Actualizar");

        jLabel5.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("RECIBIDO:");

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TOTAL: ");

        jLabel6.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CAMBIO:");

        CambioT.setEditable(false);
        CambioT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0.00#"))));
        CambioT.setText("0");

        RecibidoT.setBackground(new java.awt.Color(51, 51, 55));
        RecibidoT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0.00#"))));
        RecibidoT.setText("0");

        TotalT.setEditable(false);
        TotalT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0.00#"))));
        TotalT.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addComponent(TotalT, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                .addGap(12, 12, 12))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel6)))
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(RecibidoT)
                        .addGap(12, 12, 12))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(CambioT)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TotalT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(RecibidoT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CambioT, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(FinalizarO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CancelarO)
                        .addGap(54, 54, 54)
                        .addComponent(Actualizar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dia, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ClienteT, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComandaT, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(dia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(CancelarO)
                                .addComponent(FinalizarO)
                                .addComponent(Actualizar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ClienteT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComandaT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CancelarOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarOActionPerformed
        //limpiar();

        // TODO add your handling code here:
    }//GEN-LAST:event_CancelarOActionPerformed

    private void FinalizarOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarOActionPerformed

    }//GEN-LAST:event_FinalizarOActionPerformed

    private void ComandaTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComandaTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComandaTActionPerformed

    private void CorralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CorralActionPerformed

    private void EspecialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspecialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EspecialActionPerformed

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseMoved

    private void CcorralItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CcorralItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_CcorralItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Actualizar;
    public javax.swing.JButton Agregar;
    public javax.swing.JRadioButton Bebida;
    public javax.swing.JFormattedTextField CambioT;
    public javax.swing.JButton CancelarO;
    public javax.swing.JComboBox Ccorral;
    public javax.swing.JComboBox Cfierro;
    private javax.swing.JLabel Cliente;
    public javax.swing.JTextField ClienteT;
    public javax.swing.JTextField ComandaT;
    public javax.swing.JRadioButton Corral;
    public javax.swing.JMenuItem Duplicar;
    public javax.swing.JMenuItem Eliminar;
    public javax.swing.JRadioButton Especial;
    public javax.swing.JRadioButton Extra;
    public javax.swing.JComboBox Extras;
    public javax.swing.JLabel Fecha;
    public javax.swing.JRadioButton Fierro;
    public javax.swing.JButton FinalizarO;
    public javax.swing.JMenuItem MoverA1;
    public javax.swing.JMenuItem MoverA2;
    public javax.swing.JMenuItem MoverA3;
    public javax.swing.JMenuItem MoverA4;
    public javax.swing.JMenuItem MoverA5;
    public javax.swing.JMenuItem MoverA6;
    public javax.swing.JMenuItem MoverA7;
    public javax.swing.JComboBox Pan;
    public javax.swing.JFormattedTextField RecibidoT;
    public javax.swing.JComboBox Sabor;
    public javax.swing.JComboBox Tamaño;
    public javax.swing.JComboBox Termino;
    public javax.swing.JFormattedTextField TotalT;
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JComboBox cEspecial;
    public javax.swing.JLabel dia;
    public javax.swing.JComboBox guarnicion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    public javax.swing.JMenu mover;
    public javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
